# Generated by Django 5.2.1 on 2025-07-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='model_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='model_type',
            field=models.CharField(choices=[('beats', 'BEATs'), ('yamnet', 'YAMNet'), ('others', 'Others')], default='beats', max_length=20),
        ),
    ]
