# Generated by Django 5.2.1 on 2025-06-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotation', '0006_alter_annotation_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='optimize',
            field=models.BooleanField(default=False),
        ),
    ]
